name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions: write-all
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Certificate
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
        run: |
          echo "$MACOS_CERTIFICATE" | base64 --decode > ./macos.p12
          echo "$WINDOWS_CERTIFICATE" | base64 --decode > ./windows.pfx 

      - name: Build
        run: |
          npm install
          npm run postinstall
          npm run build   

      - name: Publish
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ./macos.p12
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          WIN_CSC_LINK: ./windows.pfx
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux

      - name: Clean
        run: |
          rm ./windows.pfx
